version: '3'

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

  backend:
    build:
      context: djangoProject
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "22:22"
#    network_mode: host

  vm1:
    build:
      context: vm
      dockerfile: Dockerfile
    ports:
      - "80:80"
        #      - "9000:9000"
  vm2:
    build:
      context: vm
      dockerfile: Dockerfile
#    ports:
#      - "9000:9000"
