#!/bin/bash

sudo apt update >/dev/null 2>&1

count=$(apt list --upgradable 2>/dev/null | grep -c "upgradable")

if [ $count -gt 0 ]; then
echo "[WARNING]There are $count updates available on your device. Updates may include security updates! "
echo "[RECOMMEND]Update the specified packages"
fi
