# Generated by Django 5.0.6 on 2024-05-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0002_script_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='category',
            field=models.CharField(choices=[('normal', 'Обычные'), ('network', 'Сетевые'), ('software', 'ПО'), ('system', 'Системные')], default='normal', max_length=100),
        ),
    ]
